apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ni4sp5pzj-java-quarkus
  janus-idp.io/tekton: ni4sp5pzj-java-quarkus
  backstage.io/kubernetes-id: ni4sp5pzj-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ni4sp5pzj-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
